
    //This file is generated by generate.ts
    import { Board } from "./board";
    import { BuildLocation } from "./buildLocation";
    export class Boards {
        static DRControlZeroG: Board = {
            friendlyName: "3DRControlZeroG",
            board: "3DRControlZeroG",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/3DRControlZeroG`
        };
static ACNSCM4Pilot: Board = {
            friendlyName: "ACNS-CM4Pilot",
            board: "ACNS-CM4Pilot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ACNS-CM4Pilot`
        };
static ACNSF405AIO: Board = {
            friendlyName: "ACNS-F405AIO",
            board: "ACNS-F405AIO",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ACNS-F405AIO`
        };
static AEDROXH7: Board = {
            friendlyName: "AEDROXH7",
            board: "AEDROXH7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AEDROXH7`
        };
static AEROFOXH7: Board = {
            friendlyName: "AEROFOX-H7",
            board: "AEROFOX-H7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AEROFOX-H7`
        };
static AETH743Basic: Board = {
            friendlyName: "AET-H743-Basic",
            board: "AET-H743-Basic",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AET-H743-Basic`
        };
static AIRLink: Board = {
            friendlyName: "AIRLink",
            board: "AIRLink",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AIRLink`
        };
static ARKV6X: Board = {
            friendlyName: "ARKV6X",
            board: "ARKV6X",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ARKV6X`
        };
static ARKV6Xbdshot: Board = {
            friendlyName: "ARKV6X-bdshot",
            board: "ARKV6X-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ARKV6X-bdshot`
        };
static ARK_FPV: Board = {
            friendlyName: "ARK_FPV",
            board: "ARK_FPV",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ARK_FPV`
        };
static ATOMRCF405NAVIDeluxe: Board = {
            friendlyName: "ATOMRCF405NAVI-Deluxe",
            board: "ATOMRCF405NAVI-Deluxe",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ATOMRCF405NAVI-Deluxe`
        };
static AcctonGodwit_GA1: Board = {
            friendlyName: "AcctonGodwit_GA1",
            board: "AcctonGodwit_GA1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AcctonGodwit_GA1`
        };
static AirvoluteDCS2: Board = {
            friendlyName: "Airvolute-DCS2",
            board: "Airvolute-DCS2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Airvolute-DCS2`
        };
static AnyleafH7: Board = {
            friendlyName: "AnyleafH7",
            board: "AnyleafH7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AnyleafH7`
        };
static AocodaRCH743Dual: Board = {
            friendlyName: "Aocoda-RC-H743Dual",
            board: "Aocoda-RC-H743Dual",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Aocoda-RC-H743Dual`
        };
static AtomRCF405NAVI: Board = {
            friendlyName: "AtomRCF405NAVI",
            board: "AtomRCF405NAVI",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AtomRCF405NAVI`
        };
static BETAFPVF405: Board = {
            friendlyName: "BETAFPV-F405",
            board: "BETAFPV-F405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BETAFPV-F405`
        };
static BETAFPVF405I2C: Board = {
            friendlyName: "BETAFPV-F405-I2C",
            board: "BETAFPV-F405-I2C",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BETAFPV-F405-I2C`
        };
static BOTWINGF405: Board = {
            friendlyName: "BOTWINGF405",
            board: "BOTWINGF405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BOTWINGF405`
        };
static BROTHERHOBBYF405v3: Board = {
            friendlyName: "BROTHERHOBBYF405v3",
            board: "BROTHERHOBBYF405v3",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BROTHERHOBBYF405v3`
        };
static BROTHERHOBBYH743: Board = {
            friendlyName: "BROTHERHOBBYH743",
            board: "BROTHERHOBBYH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BROTHERHOBBYH743`
        };
static BeastF7: Board = {
            friendlyName: "BeastF7",
            board: "BeastF7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BeastF7`
        };
static BeastF7v2: Board = {
            friendlyName: "BeastF7v2",
            board: "BeastF7v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BeastF7v2`
        };
static BeastH7: Board = {
            friendlyName: "BeastH7",
            board: "BeastH7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BeastH7`
        };
static BeastH7v2: Board = {
            friendlyName: "BeastH7v2",
            board: "BeastH7v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BeastH7v2`
        };
static BlitzF745: Board = {
            friendlyName: "BlitzF745",
            board: "BlitzF745",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BlitzF745`
        };
static BlitzF745AIO: Board = {
            friendlyName: "BlitzF745AIO",
            board: "BlitzF745AIO",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BlitzF745AIO`
        };
static BlitzH743Pro: Board = {
            friendlyName: "BlitzH743Pro",
            board: "BlitzH743Pro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BlitzH743Pro`
        };
static BlitzMiniF745: Board = {
            friendlyName: "BlitzMiniF745",
            board: "BlitzMiniF745",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BlitzMiniF745`
        };
static BlitzWingH743: Board = {
            friendlyName: "BlitzWingH743",
            board: "BlitzWingH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BlitzWingH743`
        };
static BrahmaF4: Board = {
            friendlyName: "BrahmaF4",
            board: "BrahmaF4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BrahmaF4`
        };
static CBUH7LCStamp: Board = {
            friendlyName: "CBU-H7-LC-Stamp",
            board: "CBU-H7-LC-Stamp",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CBU-H7-LC-Stamp`
        };
static CBUH7Stamp: Board = {
            friendlyName: "CBU-H7-Stamp",
            board: "CBU-H7-Stamp",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CBU-H7-Stamp`
        };
static CORVON405V2_1: Board = {
            friendlyName: "CORVON405V2_1",
            board: "CORVON405V2_1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CORVON405V2_1`
        };
static CORVON743V1: Board = {
            friendlyName: "CORVON743V1",
            board: "CORVON743V1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CORVON743V1`
        };
static CSKY405: Board = {
            friendlyName: "CSKY405",
            board: "CSKY405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CSKY405`
        };
static CUAV7Nano: Board = {
            friendlyName: "CUAV-7-Nano",
            board: "CUAV-7-Nano",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAV-7-Nano`
        };
static CUAVNora: Board = {
            friendlyName: "CUAV-Nora",
            board: "CUAV-Nora",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAV-Nora`
        };
static CUAVNorabdshot: Board = {
            friendlyName: "CUAV-Nora-bdshot",
            board: "CUAV-Nora-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAV-Nora-bdshot`
        };
static CUAVPixhackv3: Board = {
            friendlyName: "CUAV-Pixhack-v3",
            board: "CUAV-Pixhack-v3",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAV-Pixhack-v3`
        };
static CUAVV6Xv2: Board = {
            friendlyName: "CUAV-V6X-v2",
            board: "CUAV-V6X-v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAV-V6X-v2`
        };
static CUAVX25EVO: Board = {
            friendlyName: "CUAV-X25-EVO",
            board: "CUAV-X25-EVO",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAV-X25-EVO`
        };
static CUAVX7: Board = {
            friendlyName: "CUAV-X7",
            board: "CUAV-X7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAV-X7`
        };
static CUAVX7bdshot: Board = {
            friendlyName: "CUAV-X7-bdshot",
            board: "CUAV-X7-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAV-X7-bdshot`
        };
static CUAVv5: Board = {
            friendlyName: "CUAVv5",
            board: "CUAVv5",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAVv5`
        };
static CUAVv5bdshot: Board = {
            friendlyName: "CUAVv5-bdshot",
            board: "CUAVv5-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAVv5-bdshot`
        };
static CUAVv5Nano: Board = {
            friendlyName: "CUAVv5Nano",
            board: "CUAVv5Nano",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAVv5Nano`
        };
static CUAVv5Nanobdshot: Board = {
            friendlyName: "CUAVv5Nano-bdshot",
            board: "CUAVv5Nano-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAVv5Nano-bdshot`
        };
static CrazyF405: Board = {
            friendlyName: "CrazyF405",
            board: "CrazyF405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CrazyF405`
        };
static CubeBlack: Board = {
            friendlyName: "CubeBlack",
            board: "CubeBlack",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeBlack`
        };
static CubeBlackPlus: Board = {
            friendlyName: "CubeBlack+",
            board: "CubeBlack+",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeBlack+`
        };
static CubeGreensolo: Board = {
            friendlyName: "CubeGreen-solo",
            board: "CubeGreen-solo",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeGreen-solo`
        };
static CubeOrange: Board = {
            friendlyName: "CubeOrange",
            board: "CubeOrange",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange`
        };
static CubeOrangeSimOnHardWare: Board = {
            friendlyName: "CubeOrange-SimOnHardWare",
            board: "CubeOrange-SimOnHardWare",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-SimOnHardWare`
        };
static CubeOrangebdshot: Board = {
            friendlyName: "CubeOrange-bdshot",
            board: "CubeOrange-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-bdshot`
        };
static CubeOrangePlus: Board = {
            friendlyName: "CubeOrangePlus",
            board: "CubeOrangePlus",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus`
        };
static CubeOrangePlusSimOnHardWare: Board = {
            friendlyName: "CubeOrangePlus-SimOnHardWare",
            board: "CubeOrangePlus-SimOnHardWare",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-SimOnHardWare`
        };
static CubeOrangePlusbdshot: Board = {
            friendlyName: "CubeOrangePlus-bdshot",
            board: "CubeOrangePlus-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-bdshot`
        };
static CubePurple: Board = {
            friendlyName: "CubePurple",
            board: "CubePurple",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubePurple`
        };
static CubeRedPrimary: Board = {
            friendlyName: "CubeRedPrimary",
            board: "CubeRedPrimary",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeRedPrimary`
        };
static CubeRedSecondary: Board = {
            friendlyName: "CubeRedSecondary",
            board: "CubeRedSecondary",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeRedSecondary`
        };
static CubeSolo: Board = {
            friendlyName: "CubeSolo",
            board: "CubeSolo",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeSolo`
        };
static CubeYellow: Board = {
            friendlyName: "CubeYellow",
            board: "CubeYellow",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeYellow`
        };
static CubeYellowbdshot: Board = {
            friendlyName: "CubeYellow-bdshot",
            board: "CubeYellow-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeYellow-bdshot`
        };
static DAKEFPVF405: Board = {
            friendlyName: "DAKEFPVF405",
            board: "DAKEFPVF405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/DAKEFPVF405`
        };
static DAKEFPVH743: Board = {
            friendlyName: "DAKEFPVH743",
            board: "DAKEFPVH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/DAKEFPVH743`
        };
static DAKEFPVH743Pro: Board = {
            friendlyName: "DAKEFPVH743Pro",
            board: "DAKEFPVH743Pro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/DAKEFPVH743Pro`
        };
static DevEBoxH7v2: Board = {
            friendlyName: "DevEBoxH7v2",
            board: "DevEBoxH7v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/DevEBoxH7v2`
        };
static DroneerF405: Board = {
            friendlyName: "DroneerF405",
            board: "DroneerF405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/DroneerF405`
        };
static DrotekP3Pro: Board = {
            friendlyName: "DrotekP3Pro",
            board: "DrotekP3Pro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/DrotekP3Pro`
        };
static Durandal: Board = {
            friendlyName: "Durandal",
            board: "Durandal",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Durandal`
        };
static Durandalbdshot: Board = {
            friendlyName: "Durandal-bdshot",
            board: "Durandal-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Durandal-bdshot`
        };
static F35Lightning: Board = {
            friendlyName: "F35Lightning",
            board: "F35Lightning",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/F35Lightning`
        };
static F4BY: Board = {
            friendlyName: "F4BY",
            board: "F4BY",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/F4BY`
        };
static F4BY_F427: Board = {
            friendlyName: "F4BY_F427",
            board: "F4BY_F427",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/F4BY_F427`
        };
static FlyingMoonF407: Board = {
            friendlyName: "FlyingMoonF407",
            board: "FlyingMoonF407",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FlyingMoonF407`
        };
static FlyingMoonF427: Board = {
            friendlyName: "FlyingMoonF427",
            board: "FlyingMoonF427",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FlyingMoonF427`
        };
static FlyingMoonH743: Board = {
            friendlyName: "FlyingMoonH743",
            board: "FlyingMoonH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FlyingMoonH743`
        };
static FlywooF405HDAIOv2: Board = {
            friendlyName: "FlywooF405HD-AIOv2",
            board: "FlywooF405HD-AIOv2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2`
        };
static FlywooF405Pro: Board = {
            friendlyName: "FlywooF405Pro",
            board: "FlywooF405Pro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FlywooF405Pro`
        };
static FlywooF405SAIO: Board = {
            friendlyName: "FlywooF405S-AIO",
            board: "FlywooF405S-AIO",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FlywooF405S-AIO`
        };
static FlywooF745: Board = {
            friendlyName: "FlywooF745",
            board: "FlywooF745",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FlywooF745`
        };
static FlywooF745Nano: Board = {
            friendlyName: "FlywooF745Nano",
            board: "FlywooF745Nano",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FlywooF745Nano`
        };
static FlywooH743Pro: Board = {
            friendlyName: "FlywooH743Pro",
            board: "FlywooH743Pro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FlywooH743Pro`
        };
static FoxeerF405v2: Board = {
            friendlyName: "FoxeerF405v2",
            board: "FoxeerF405v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FoxeerF405v2`
        };
static FoxeerH743v1: Board = {
            friendlyName: "FoxeerH743v1",
            board: "FoxeerH743v1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FoxeerH743v1`
        };
static GEPRCF745BTHD: Board = {
            friendlyName: "GEPRCF745BTHD",
            board: "GEPRCF745BTHD",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/GEPRCF745BTHD`
        };
static GEPRC_TAKER_H743: Board = {
            friendlyName: "GEPRC_TAKER_H743",
            board: "GEPRC_TAKER_H743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/GEPRC_TAKER_H743`
        };
static GreenSightUltraBlue: Board = {
            friendlyName: "GreenSightUltraBlue",
            board: "GreenSightUltraBlue",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/GreenSightUltraBlue`
        };
static Here4FC: Board = {
            friendlyName: "Here4FC",
            board: "Here4FC",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Here4FC`
        };
static IFLIGHT_2RAW_H7: Board = {
            friendlyName: "IFLIGHT_2RAW_H7",
            board: "IFLIGHT_2RAW_H7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/IFLIGHT_2RAW_H7`
        };
static JFB100: Board = {
            friendlyName: "JFB100",
            board: "JFB100",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/JFB100`
        };
static JFB110: Board = {
            friendlyName: "JFB110",
            board: "JFB110",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/JFB110`
        };
static JHEMCUGSF405A: Board = {
            friendlyName: "JHEMCU-GSF405A",
            board: "JHEMCU-GSF405A",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/JHEMCU-GSF405A`
        };
static JHEMCUGSF405ARX2: Board = {
            friendlyName: "JHEMCU-GSF405A-RX2",
            board: "JHEMCU-GSF405A-RX2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/JHEMCU-GSF405A-RX2`
        };
static JHEMCUH743HD: Board = {
            friendlyName: "JHEMCU-H743HD",
            board: "JHEMCU-H743HD",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/JHEMCU-H743HD`
        };
static JHEMCUF405PRO: Board = {
            friendlyName: "JHEMCUF405PRO",
            board: "JHEMCUF405PRO",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/JHEMCUF405PRO`
        };
static JHEMCUF405WING: Board = {
            friendlyName: "JHEMCUF405WING",
            board: "JHEMCUF405WING",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/JHEMCUF405WING`
        };
static JHEM_JHEF405: Board = {
            friendlyName: "JHEM_JHEF405",
            board: "JHEM_JHEF405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/JHEM_JHEF405`
        };
static KakuteF4: Board = {
            friendlyName: "KakuteF4",
            board: "KakuteF4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteF4`
        };
static KakuteF4Wing: Board = {
            friendlyName: "KakuteF4-Wing",
            board: "KakuteF4-Wing",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteF4-Wing`
        };
static KakuteF4Mini: Board = {
            friendlyName: "KakuteF4Mini",
            board: "KakuteF4Mini",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteF4Mini`
        };
static KakuteF7: Board = {
            friendlyName: "KakuteF7",
            board: "KakuteF7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteF7`
        };
static KakuteF7bdshot: Board = {
            friendlyName: "KakuteF7-bdshot",
            board: "KakuteF7-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteF7-bdshot`
        };
static KakuteF7Mini: Board = {
            friendlyName: "KakuteF7Mini",
            board: "KakuteF7Mini",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteF7Mini`
        };
static KakuteH7: Board = {
            friendlyName: "KakuteH7",
            board: "KakuteH7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteH7`
        };
static KakuteH7Wing: Board = {
            friendlyName: "KakuteH7-Wing",
            board: "KakuteH7-Wing",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteH7-Wing`
        };
static KakuteH7bdshot: Board = {
            friendlyName: "KakuteH7-bdshot",
            board: "KakuteH7-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteH7-bdshot`
        };
static KakuteH7Mini: Board = {
            friendlyName: "KakuteH7Mini",
            board: "KakuteH7Mini",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini`
        };
static KakuteH7MiniNand: Board = {
            friendlyName: "KakuteH7Mini-Nand",
            board: "KakuteH7Mini-Nand",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini-Nand`
        };
static KakuteH7v2: Board = {
            friendlyName: "KakuteH7v2",
            board: "KakuteH7v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/KakuteH7v2`
        };
static LongBowF405WING: Board = {
            friendlyName: "LongBowF405WING",
            board: "LongBowF405WING",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/LongBowF405WING`
        };
static LumenierLUXF765NDAA: Board = {
            friendlyName: "LumenierLUXF765-NDAA",
            board: "LumenierLUXF765-NDAA",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/LumenierLUXF765-NDAA`
        };
static MFTSEMA100: Board = {
            friendlyName: "MFT-SEMA100",
            board: "MFT-SEMA100",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MFT-SEMA100`
        };
static MUPilot: Board = {
            friendlyName: "MUPilot",
            board: "MUPilot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MUPilot`
        };
static MambaF4052022: Board = {
            friendlyName: "MambaF405-2022",
            board: "MambaF405-2022",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MambaF405-2022`
        };
static MambaF405USI2C: Board = {
            friendlyName: "MambaF405US-I2C",
            board: "MambaF405US-I2C",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MambaF405US-I2C`
        };
static MambaF405v2: Board = {
            friendlyName: "MambaF405v2",
            board: "MambaF405v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MambaF405v2`
        };
static MambaH743v4: Board = {
            friendlyName: "MambaH743v4",
            board: "MambaH743v4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MambaH743v4`
        };
static MatekF405: Board = {
            friendlyName: "MatekF405",
            board: "MatekF405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF405`
        };
static MatekF405CAN: Board = {
            friendlyName: "MatekF405-CAN",
            board: "MatekF405-CAN",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN`
        };
static MatekF405STD: Board = {
            friendlyName: "MatekF405-STD",
            board: "MatekF405-STD",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF405-STD`
        };
static MatekF405TE: Board = {
            friendlyName: "MatekF405-TE",
            board: "MatekF405-TE",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF405-TE`
        };
static MatekF405TEbdshot: Board = {
            friendlyName: "MatekF405-TE-bdshot",
            board: "MatekF405-TE-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF405-TE-bdshot`
        };
static MatekF405Wing: Board = {
            friendlyName: "MatekF405-Wing",
            board: "MatekF405-Wing",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing`
        };
static MatekF405Wingbdshot: Board = {
            friendlyName: "MatekF405-Wing-bdshot",
            board: "MatekF405-Wing-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing-bdshot`
        };
static MatekF405bdshot: Board = {
            friendlyName: "MatekF405-bdshot",
            board: "MatekF405-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF405-bdshot`
        };
static MatekF765SE: Board = {
            friendlyName: "MatekF765-SE",
            board: "MatekF765-SE",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF765-SE`
        };
static MatekF765Wing: Board = {
            friendlyName: "MatekF765-Wing",
            board: "MatekF765-Wing",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF765-Wing`
        };
static MatekF765Wingbdshot: Board = {
            friendlyName: "MatekF765-Wing-bdshot",
            board: "MatekF765-Wing-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekF765-Wing-bdshot`
        };
static MatekH743: Board = {
            friendlyName: "MatekH743",
            board: "MatekH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekH743`
        };
static MatekH743bdshot: Board = {
            friendlyName: "MatekH743-bdshot",
            board: "MatekH743-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekH743-bdshot`
        };
static MatekH7A3: Board = {
            friendlyName: "MatekH7A3",
            board: "MatekH7A3",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekH7A3`
        };
static MicoAir405Mini: Board = {
            friendlyName: "MicoAir405Mini",
            board: "MicoAir405Mini",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MicoAir405Mini`
        };
static MicoAir405v2: Board = {
            friendlyName: "MicoAir405v2",
            board: "MicoAir405v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2`
        };
static MicoAir743: Board = {
            friendlyName: "MicoAir743",
            board: "MicoAir743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MicoAir743`
        };
static MicoAir743AIO: Board = {
            friendlyName: "MicoAir743-AIO",
            board: "MicoAir743-AIO",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MicoAir743-AIO`
        };
static MicoAir743v2: Board = {
            friendlyName: "MicoAir743v2",
            board: "MicoAir743v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MicoAir743v2`
        };
static NarinFCH5: Board = {
            friendlyName: "NarinFC-H5",
            board: "NarinFC-H5",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/NarinFC-H5`
        };
static NarinFCH7: Board = {
            friendlyName: "NarinFC-H7",
            board: "NarinFC-H7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/NarinFC-H7`
        };
static NxtPX4v2: Board = {
            friendlyName: "NxtPX4v2",
            board: "NxtPX4v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/NxtPX4v2`
        };
static OMNIBUSF7V2: Board = {
            friendlyName: "OMNIBUSF7V2",
            board: "OMNIBUSF7V2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/OMNIBUSF7V2`
        };
static ORBITH743: Board = {
            friendlyName: "ORBITH743",
            board: "ORBITH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ORBITH743`
        };
static OmnibusNanoV6: Board = {
            friendlyName: "OmnibusNanoV6",
            board: "OmnibusNanoV6",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/OmnibusNanoV6`
        };
static OmnibusNanoV6bdshot: Board = {
            friendlyName: "OmnibusNanoV6-bdshot",
            board: "OmnibusNanoV6-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/OmnibusNanoV6-bdshot`
        };
static OrqaF405Pro: Board = {
            friendlyName: "OrqaF405Pro",
            board: "OrqaF405Pro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/OrqaF405Pro`
        };
static OrqaH743Pro: Board = {
            friendlyName: "OrqaH743Pro",
            board: "OrqaH743Pro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/OrqaH743Pro`
        };
static PH4mini: Board = {
            friendlyName: "PH4-mini",
            board: "PH4-mini",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PH4-mini`
        };
static PH4minibdshot: Board = {
            friendlyName: "PH4-mini-bdshot",
            board: "PH4-mini-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PH4-mini-bdshot`
        };
static Pix32v5: Board = {
            friendlyName: "Pix32v5",
            board: "Pix32v5",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pix32v5`
        };
static PixC4Jetson: Board = {
            friendlyName: "PixC4-Jetson",
            board: "PixC4-Jetson",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PixC4-Jetson`
        };
static PixFlamingo: Board = {
            friendlyName: "PixFlamingo",
            board: "PixFlamingo",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PixFlamingo`
        };
static PixFlamingoF767: Board = {
            friendlyName: "PixFlamingo-F767",
            board: "PixFlamingo-F767",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PixFlamingo-F767`
        };
static PixPilotC3: Board = {
            friendlyName: "PixPilot-C3",
            board: "PixPilot-C3",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PixPilot-C3`
        };
static PixPilotV3: Board = {
            friendlyName: "PixPilot-V3",
            board: "PixPilot-V3",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PixPilot-V3`
        };
static PixPilotV6: Board = {
            friendlyName: "PixPilot-V6",
            board: "PixPilot-V6",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PixPilot-V6`
        };
static PixPilotV6PRO: Board = {
            friendlyName: "PixPilot-V6PRO",
            board: "PixPilot-V6PRO",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PixPilot-V6PRO`
        };
static PixSurveyA1: Board = {
            friendlyName: "PixSurveyA1",
            board: "PixSurveyA1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PixSurveyA1`
        };
static PixSurveyA1IND: Board = {
            friendlyName: "PixSurveyA1-IND",
            board: "PixSurveyA1-IND",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PixSurveyA1-IND`
        };
static PixSurveyA2IND: Board = {
            friendlyName: "PixSurveyA2-IND",
            board: "PixSurveyA2-IND",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/PixSurveyA2-IND`
        };
static Pixhawk1: Board = {
            friendlyName: "Pixhawk1",
            board: "Pixhawk1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1`
        };
static Pixhawk11M: Board = {
            friendlyName: "Pixhawk1-1M",
            board: "Pixhawk1-1M",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-1M`
        };
static Pixhawk11Mbdshot: Board = {
            friendlyName: "Pixhawk1-1M-bdshot",
            board: "Pixhawk1-1M-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-1M-bdshot`
        };
static Pixhawk1bdshot: Board = {
            friendlyName: "Pixhawk1-bdshot",
            board: "Pixhawk1-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-bdshot`
        };
static Pixhawk4: Board = {
            friendlyName: "Pixhawk4",
            board: "Pixhawk4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk4`
        };
static Pixhawk4bdshot: Board = {
            friendlyName: "Pixhawk4-bdshot",
            board: "Pixhawk4-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk4-bdshot`
        };
static Pixhawk5X: Board = {
            friendlyName: "Pixhawk5X",
            board: "Pixhawk5X",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk5X`
        };
static Pixhawk6C: Board = {
            friendlyName: "Pixhawk6C",
            board: "Pixhawk6C",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6C`
        };
static Pixhawk6Cbdshot: Board = {
            friendlyName: "Pixhawk6C-bdshot",
            board: "Pixhawk6C-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6C-bdshot`
        };
static Pixhawk6X: Board = {
            friendlyName: "Pixhawk6X",
            board: "Pixhawk6X",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6X`
        };
static Pixhawk6Xbdshot: Board = {
            friendlyName: "Pixhawk6X-bdshot",
            board: "Pixhawk6X-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6X-bdshot`
        };
static Pixracer: Board = {
            friendlyName: "Pixracer",
            board: "Pixracer",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixracer`
        };
static Pixracerbdshot: Board = {
            friendlyName: "Pixracer-bdshot",
            board: "Pixracer-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixracer-bdshot`
        };
static QioTekAdeptF407: Board = {
            friendlyName: "QioTekAdeptF407",
            board: "QioTekAdeptF407",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/QioTekAdeptF407`
        };
static QioTekZealotF427: Board = {
            friendlyName: "QioTekZealotF427",
            board: "QioTekZealotF427",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/QioTekZealotF427`
        };
static QioTekZealotH743: Board = {
            friendlyName: "QioTekZealotH743",
            board: "QioTekZealotH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/QioTekZealotH743`
        };
static QioTekZealotH743bdshot: Board = {
            friendlyName: "QioTekZealotH743-bdshot",
            board: "QioTekZealotH743-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/QioTekZealotH743-bdshot`
        };
static R9Pilot: Board = {
            friendlyName: "R9Pilot",
            board: "R9Pilot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/R9Pilot`
        };
static RADIX2HD: Board = {
            friendlyName: "RADIX2HD",
            board: "RADIX2HD",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD`
        };
static RadiolinkPIX6: Board = {
            friendlyName: "RadiolinkPIX6",
            board: "RadiolinkPIX6",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/RadiolinkPIX6`
        };
static ReaperF745: Board = {
            friendlyName: "ReaperF745",
            board: "ReaperF745",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ReaperF745`
        };
static SDMODELH7V1: Board = {
            friendlyName: "SDMODELH7V1",
            board: "SDMODELH7V1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V1`
        };
static SDMODELH7V2: Board = {
            friendlyName: "SDMODELH7V2",
            board: "SDMODELH7V2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V2`
        };
static SITL_arm_linux_gnueabihf: Board = {
            friendlyName: "SITL_arm_linux_gnueabihf",
            board: "SITL_arm_linux_gnueabihf",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SITL_arm_linux_gnueabihf`
        };
static SITL_x86_64_linux_gnu: Board = {
            friendlyName: "SITL_x86_64_linux_gnu",
            board: "SITL_x86_64_linux_gnu",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SITL_x86_64_linux_gnu`
        };
static SIYI_N7: Board = {
            friendlyName: "SIYI_N7",
            board: "SIYI_N7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SIYI_N7`
        };
static SPEDIXF405: Board = {
            friendlyName: "SPEDIXF405",
            board: "SPEDIXF405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SPEDIXF405`
        };
static SPEDIXH743: Board = {
            friendlyName: "SPEDIXH743",
            board: "SPEDIXH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SPEDIXH743`
        };
static SPRacingH7: Board = {
            friendlyName: "SPRacingH7",
            board: "SPRacingH7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SPRacingH7`
        };
static SPRacingH7RF: Board = {
            friendlyName: "SPRacingH7RF",
            board: "SPRacingH7RF",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SPRacingH7RF`
        };
static SULILGH7P1P2: Board = {
            friendlyName: "SULILGH7-P1-P2",
            board: "SULILGH7-P1-P2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SULILGH7-P1-P2`
        };
static SVehicleE2: Board = {
            friendlyName: "SVehicle-E2",
            board: "SVehicle-E2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SVehicle-E2`
        };
static SequreH743: Board = {
            friendlyName: "SequreH743",
            board: "SequreH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SequreH743`
        };
static SkySakuraH743: Board = {
            friendlyName: "SkySakuraH743",
            board: "SkySakuraH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743`
        };
static SkystarsF405v2: Board = {
            friendlyName: "SkystarsF405v2",
            board: "SkystarsF405v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SkystarsF405v2`
        };
static SkystarsH7HDbdshot: Board = {
            friendlyName: "SkystarsH7HD-bdshot",
            board: "SkystarsH7HD-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SkystarsH7HD-bdshot`
        };
static SkystarsH7HDv2: Board = {
            friendlyName: "SkystarsH7HDv2",
            board: "SkystarsH7HDv2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SkystarsH7HDv2`
        };
static SpeedyBeeF405AIO: Board = {
            friendlyName: "SpeedyBeeF405AIO",
            board: "SpeedyBeeF405AIO",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SpeedyBeeF405AIO`
        };
static SpeedyBeeF405Mini: Board = {
            friendlyName: "SpeedyBeeF405Mini",
            board: "SpeedyBeeF405Mini",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SpeedyBeeF405Mini`
        };
static SpeedyBeeF405WING: Board = {
            friendlyName: "SpeedyBeeF405WING",
            board: "SpeedyBeeF405WING",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SpeedyBeeF405WING`
        };
static StellarF4: Board = {
            friendlyName: "StellarF4",
            board: "StellarF4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/StellarF4`
        };
static StellarF4V2: Board = {
            friendlyName: "StellarF4V2",
            board: "StellarF4V2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/StellarF4V2`
        };
static StellarH7V2: Board = {
            friendlyName: "StellarH7V2",
            board: "StellarH7V2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2`
        };
static SuccexF4: Board = {
            friendlyName: "SuccexF4",
            board: "SuccexF4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/SuccexF4`
        };
static TBSColibriF7: Board = {
            friendlyName: "TBS-Colibri-F7",
            board: "TBS-Colibri-F7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/TBS-Colibri-F7`
        };
static TBS_LUCID_H7: Board = {
            friendlyName: "TBS_LUCID_H7",
            board: "TBS_LUCID_H7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_H7`
        };
static TBS_LUCID_H7_WING: Board = {
            friendlyName: "TBS_LUCID_H7_WING",
            board: "TBS_LUCID_H7_WING",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_H7_WING`
        };
static TBS_LUCID_PRO: Board = {
            friendlyName: "TBS_LUCID_PRO",
            board: "TBS_LUCID_PRO",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/TBS_LUCID_PRO`
        };
static TMotorH743: Board = {
            friendlyName: "TMotorH743",
            board: "TMotorH743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/TMotorH743`
        };
static VRBrainv51: Board = {
            friendlyName: "VRBrain-v51",
            board: "VRBrain-v51",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/VRBrain-v51`
        };
static VRBrainv52: Board = {
            friendlyName: "VRBrain-v52",
            board: "VRBrain-v52",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/VRBrain-v52`
        };
static VRBrainv54: Board = {
            friendlyName: "VRBrain-v54",
            board: "VRBrain-v54",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/VRBrain-v54`
        };
static VRCorev10: Board = {
            friendlyName: "VRCore-v10",
            board: "VRCore-v10",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/VRCore-v10`
        };
static VRUBrainv51: Board = {
            friendlyName: "VRUBrain-v51",
            board: "VRUBrain-v51",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/VRUBrain-v51`
        };
static VUAVV7pro: Board = {
            friendlyName: "VUAV-V7pro",
            board: "VUAV-V7pro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/VUAV-V7pro`
        };
static XMAVAPH743v2: Board = {
            friendlyName: "X-MAV-AP-H743v2",
            board: "X-MAV-AP-H743v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/X-MAV-AP-H743v2`
        };
static YARIV6X: Board = {
            friendlyName: "YARIV6X",
            board: "YARIV6X",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/YARIV6X`
        };
static YJUAV_A6: Board = {
            friendlyName: "YJUAV_A6",
            board: "YJUAV_A6",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6`
        };
static YJUAV_A6SE: Board = {
            friendlyName: "YJUAV_A6SE",
            board: "YJUAV_A6SE",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE`
        };
static YJUAV_A6SE_H743: Board = {
            friendlyName: "YJUAV_A6SE_H743",
            board: "YJUAV_A6SE_H743",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE_H743`
        };
static YJUAV_A6Ultra: Board = {
            friendlyName: "YJUAV_A6Ultra",
            board: "YJUAV_A6Ultra",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6Ultra`
        };
static ZeroOneX6: Board = {
            friendlyName: "ZeroOneX6",
            board: "ZeroOneX6",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ZeroOneX6`
        };
static ZeroOneX6_Air: Board = {
            friendlyName: "ZeroOneX6_Air",
            board: "ZeroOneX6_Air",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ZeroOneX6_Air`
        };
static aero: Board = {
            friendlyName: "aero",
            board: "aero",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/aero`
        };
static airbotf4: Board = {
            friendlyName: "airbotf4",
            board: "airbotf4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/airbotf4`
        };
static bbbmini: Board = {
            friendlyName: "bbbmini",
            board: "bbbmini",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/bbbmini`
        };
static bebop: Board = {
            friendlyName: "bebop",
            board: "bebop",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/bebop`
        };
static bhat: Board = {
            friendlyName: "bhat",
            board: "bhat",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/bhat`
        };
static blue: Board = {
            friendlyName: "blue",
            board: "blue",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/blue`
        };
static canzero: Board = {
            friendlyName: "canzero",
            board: "canzero",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/canzero`
        };
static crazyflie2: Board = {
            friendlyName: "crazyflie2",
            board: "crazyflie2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/crazyflie2`
        };
static dark: Board = {
            friendlyName: "dark",
            board: "dark",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/dark`
        };
static edge: Board = {
            friendlyName: "edge",
            board: "edge",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/edge`
        };
static erleboard: Board = {
            friendlyName: "erleboard",
            board: "erleboard",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/erleboard`
        };
static erlebrain2: Board = {
            friendlyName: "erlebrain2",
            board: "erlebrain2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/erlebrain2`
        };
static esp32buzz: Board = {
            friendlyName: "esp32buzz",
            board: "esp32buzz",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/esp32buzz`
        };
static esp32diy: Board = {
            friendlyName: "esp32diy",
            board: "esp32diy",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/esp32diy`
        };
static esp32empty: Board = {
            friendlyName: "esp32empty",
            board: "esp32empty",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/esp32empty`
        };
static esp32icarus: Board = {
            friendlyName: "esp32icarus",
            board: "esp32icarus",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/esp32icarus`
        };
static esp32imu_module_v11: Board = {
            friendlyName: "esp32imu_module_v11",
            board: "esp32imu_module_v11",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/esp32imu_module_v11`
        };
static esp32nick: Board = {
            friendlyName: "esp32nick",
            board: "esp32nick",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/esp32nick`
        };
static esp32s3devkit: Board = {
            friendlyName: "esp32s3devkit",
            board: "esp32s3devkit",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/esp32s3devkit`
        };
static esp32s3empty: Board = {
            friendlyName: "esp32s3empty",
            board: "esp32s3empty",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/esp32s3empty`
        };
static esp32s3m5stampfly: Board = {
            friendlyName: "esp32s3m5stampfly",
            board: "esp32s3m5stampfly",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/esp32s3m5stampfly`
        };
static esp32tomte76: Board = {
            friendlyName: "esp32tomte76",
            board: "esp32tomte76",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/esp32tomte76`
        };
static fmuv2: Board = {
            friendlyName: "fmuv2",
            board: "fmuv2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/fmuv2`
        };
static fmuv3: Board = {
            friendlyName: "fmuv3",
            board: "fmuv3",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/fmuv3`
        };
static fmuv5: Board = {
            friendlyName: "fmuv5",
            board: "fmuv5",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/fmuv5`
        };
static linux: Board = {
            friendlyName: "linux",
            board: "linux",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/linux`
        };
static luminousbee5: Board = {
            friendlyName: "luminousbee5",
            board: "luminousbee5",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/luminousbee5`
        };
static mRoCZeroOEMH7bdshot: Board = {
            friendlyName: "mRoCZeroOEMH7-bdshot",
            board: "mRoCZeroOEMH7-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoCZeroOEMH7-bdshot`
        };
static mRoControlZeroClassic: Board = {
            friendlyName: "mRoControlZeroClassic",
            board: "mRoControlZeroClassic",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoControlZeroClassic`
        };
static mRoControlZeroF7: Board = {
            friendlyName: "mRoControlZeroF7",
            board: "mRoControlZeroF7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoControlZeroF7`
        };
static mRoControlZeroH7: Board = {
            friendlyName: "mRoControlZeroH7",
            board: "mRoControlZeroH7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoControlZeroH7`
        };
static mRoControlZeroH7bdshot: Board = {
            friendlyName: "mRoControlZeroH7-bdshot",
            board: "mRoControlZeroH7-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoControlZeroH7-bdshot`
        };
static mRoControlZeroOEMH7: Board = {
            friendlyName: "mRoControlZeroOEMH7",
            board: "mRoControlZeroOEMH7",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoControlZeroOEMH7`
        };
static mRoNexus: Board = {
            friendlyName: "mRoNexus",
            board: "mRoNexus",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoNexus`
        };
static mRoPixracerPro: Board = {
            friendlyName: "mRoPixracerPro",
            board: "mRoPixracerPro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoPixracerPro`
        };
static mRoPixracerProbdshot: Board = {
            friendlyName: "mRoPixracerPro-bdshot",
            board: "mRoPixracerPro-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoPixracerPro-bdshot`
        };
static mRoX21: Board = {
            friendlyName: "mRoX21",
            board: "mRoX21",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoX21`
        };
static mRoX21777: Board = {
            friendlyName: "mRoX21-777",
            board: "mRoX21-777",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoX21-777`
        };
static mindpxv2: Board = {
            friendlyName: "mindpx-v2",
            board: "mindpx-v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mindpx-v2`
        };
static minipix: Board = {
            friendlyName: "mini-pix",
            board: "mini-pix",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mini-pix`
        };
static modalai_fcv1: Board = {
            friendlyName: "modalai_fc-v1",
            board: "modalai_fc-v1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/modalai_fc-v1`
        };
static navigator: Board = {
            friendlyName: "navigator",
            board: "navigator",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/navigator`
        };
static navigator64: Board = {
            friendlyName: "navigator64",
            board: "navigator64",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/navigator64`
        };
static navio: Board = {
            friendlyName: "navio",
            board: "navio",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/navio`
        };
static navio2: Board = {
            friendlyName: "navio2",
            board: "navio2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/navio2`
        };
static obal: Board = {
            friendlyName: "obal",
            board: "obal",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/obal`
        };
static ocpoc_zynq: Board = {
            friendlyName: "ocpoc_zynq",
            board: "ocpoc_zynq",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ocpoc_zynq`
        };
static omnibusf4: Board = {
            friendlyName: "omnibusf4",
            board: "omnibusf4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/omnibusf4`
        };
static omnibusf4pro: Board = {
            friendlyName: "omnibusf4pro",
            board: "omnibusf4pro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro`
        };
static omnibusf4probdshot: Board = {
            friendlyName: "omnibusf4pro-bdshot",
            board: "omnibusf4pro-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro-bdshot`
        };
static omnibusf4v6: Board = {
            friendlyName: "omnibusf4v6",
            board: "omnibusf4v6",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/omnibusf4v6`
        };
static pilotpi: Board = {
            friendlyName: "pilotpi",
            board: "pilotpi",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/pilotpi`
        };
static pocket: Board = {
            friendlyName: "pocket",
            board: "pocket",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/pocket`
        };
static pxf: Board = {
            friendlyName: "pxf",
            board: "pxf",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/pxf`
        };
static pxfmini: Board = {
            friendlyName: "pxfmini",
            board: "pxfmini",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/pxfmini`
        };
static revomini: Board = {
            friendlyName: "revo-mini",
            board: "revo-mini",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/revo-mini`
        };
static revominibdshot: Board = {
            friendlyName: "revo-mini-bdshot",
            board: "revo-mini-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/revo-mini-bdshot`
        };
static revominii2c: Board = {
            friendlyName: "revo-mini-i2c",
            board: "revo-mini-i2c",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/revo-mini-i2c`
        };
static revominii2cbdshot: Board = {
            friendlyName: "revo-mini-i2c-bdshot",
            board: "revo-mini-i2c-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/revo-mini-i2c-bdshot`
        };
static rst_zynq: Board = {
            friendlyName: "rst_zynq",
            board: "rst_zynq",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/rst_zynq`
        };
static skyviperjourney: Board = {
            friendlyName: "skyviper-journey",
            board: "skyviper-journey",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/skyviper-journey`
        };
static skyviperv2450: Board = {
            friendlyName: "skyviper-v2450",
            board: "skyviper-v2450",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450`
        };
static sparky2: Board = {
            friendlyName: "sparky2",
            board: "sparky2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/sparky2`
        };
static speedybeef4: Board = {
            friendlyName: "speedybeef4",
            board: "speedybeef4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/speedybeef4`
        };
static speedybeef4v3: Board = {
            friendlyName: "speedybeef4v3",
            board: "speedybeef4v3",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/speedybeef4v3`
        };
static speedybeef4v4: Board = {
            friendlyName: "speedybeef4v4",
            board: "speedybeef4v4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/speedybeef4v4`
        };
static thepeachk1: Board = {
            friendlyName: "thepeach-k1",
            board: "thepeach-k1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/thepeach-k1`
        };
static thepeachr1: Board = {
            friendlyName: "thepeach-r1",
            board: "thepeach-r1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/thepeach-r1`
        };
static uavdevfcum982: Board = {
            friendlyName: "uav-dev-fc-um982",
            board: "uav-dev-fc-um982",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/uav-dev-fc-um982`
        };
static vnav: Board = {
            friendlyName: "vnav",
            board: "vnav",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/vnav`
        };
static zynq: Board = {
            friendlyName: "zynq",
            board: "zynq",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/zynq`
        };
static HEEWINGF405: Board = {
            friendlyName: "HEEWING-F405",
            board: "HEEWING-F405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/HEEWING-F405`
        };
static HEEWINGF405v2: Board = {
            friendlyName: "HEEWING-F405v2",
            board: "HEEWING-F405v2",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/HEEWING-F405v2`
        };
static SwanK1: Board = {
            friendlyName: "Swan-K1",
            board: "Swan-K1",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Swan-K1`
        };
static disco: Board = {
            friendlyName: "disco",
            board: "disco",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/disco`
        };
static ARF407SmartBat: Board = {
            friendlyName: "AR-F407SmartBat",
            board: "AR-F407SmartBat",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AR-F407SmartBat`
        };
static ARK_CANNODE: Board = {
            friendlyName: "ARK_CANNODE",
            board: "ARK_CANNODE",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ARK_CANNODE`
        };
static ARK_GPS: Board = {
            friendlyName: "ARK_GPS",
            board: "ARK_GPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ARK_GPS`
        };
static ARK_RTK_GPS: Board = {
            friendlyName: "ARK_RTK_GPS",
            board: "ARK_RTK_GPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ARK_RTK_GPS`
        };
static AeroFoxAirspeed: Board = {
            friendlyName: "AeroFox-Airspeed",
            board: "AeroFox-Airspeed",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AeroFox-Airspeed`
        };
static AeroFoxAirspeedDLVR: Board = {
            friendlyName: "AeroFox-Airspeed-DLVR",
            board: "AeroFox-Airspeed-DLVR",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AeroFox-Airspeed-DLVR`
        };
static AeroFoxGNSS_F9P: Board = {
            friendlyName: "AeroFox-GNSS_F9P",
            board: "AeroFox-GNSS_F9P",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AeroFox-GNSS_F9P`
        };
static AeroFoxPMU: Board = {
            friendlyName: "AeroFox-PMU",
            board: "AeroFox-PMU",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/AeroFox-PMU`
        };
static BirdCANdy: Board = {
            friendlyName: "BirdCANdy",
            board: "BirdCANdy",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BirdCANdy`
        };
static BotBloxDroneNet: Board = {
            friendlyName: "BotBloxDroneNet",
            board: "BotBloxDroneNet",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/BotBloxDroneNet`
        };
static CRTK2HP: Board = {
            friendlyName: "C-RTK2-HP",
            board: "C-RTK2-HP",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/C-RTK2-HP`
        };
static CUAV_GPS: Board = {
            friendlyName: "CUAV_GPS",
            board: "CUAV_GPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CUAV_GPS`
        };
static CarbonixF405: Board = {
            friendlyName: "CarbonixF405",
            board: "CarbonixF405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CarbonixF405`
        };
static CubeBlackperiph: Board = {
            friendlyName: "CubeBlack-periph",
            board: "CubeBlack-periph",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeBlack-periph`
        };
static CubeNode: Board = {
            friendlyName: "CubeNode",
            board: "CubeNode",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeNode`
        };
static CubeNodeETH: Board = {
            friendlyName: "CubeNode-ETH",
            board: "CubeNode-ETH",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeNode-ETH`
        };
static CubeOrangeperiph: Board = {
            friendlyName: "CubeOrange-periph",
            board: "CubeOrange-periph",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-periph`
        };
static CubeRedPrimaryPPPGW: Board = {
            friendlyName: "CubeRedPrimary-PPPGW",
            board: "CubeRedPrimary-PPPGW",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/CubeRedPrimary-PPPGW`
        };
static FreeflyRTK: Board = {
            friendlyName: "FreeflyRTK",
            board: "FreeflyRTK",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/FreeflyRTK`
        };
static Here4AP: Board = {
            friendlyName: "Here4AP",
            board: "Here4AP",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Here4AP`
        };
static HitecAirspeed: Board = {
            friendlyName: "Hitec-Airspeed",
            board: "Hitec-Airspeed",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Hitec-Airspeed`
        };
static HitecMosaic: Board = {
            friendlyName: "HitecMosaic",
            board: "HitecMosaic",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/HitecMosaic`
        };
static HolybroF4_PMU: Board = {
            friendlyName: "HolybroF4_PMU",
            board: "HolybroF4_PMU",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/HolybroF4_PMU`
        };
static HolybroG4_Airspeed: Board = {
            friendlyName: "HolybroG4_Airspeed",
            board: "HolybroG4_Airspeed",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/HolybroG4_Airspeed`
        };
static HolybroG4_Compass: Board = {
            friendlyName: "HolybroG4_Compass",
            board: "HolybroG4_Compass",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/HolybroG4_Compass`
        };
static HolybroG4_GPS: Board = {
            friendlyName: "HolybroG4_GPS",
            board: "HolybroG4_GPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/HolybroG4_GPS`
        };
static HolybroGPS: Board = {
            friendlyName: "HolybroGPS",
            board: "HolybroGPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/HolybroGPS`
        };
static MFE_AirSpeed_CAN: Board = {
            friendlyName: "MFE_AirSpeed_CAN",
            board: "MFE_AirSpeed_CAN",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MFE_AirSpeed_CAN`
        };
static MFE_PDB_CAN: Board = {
            friendlyName: "MFE_PDB_CAN",
            board: "MFE_PDB_CAN",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MFE_PDB_CAN`
        };
static MFE_POS3_CAN: Board = {
            friendlyName: "MFE_POS3_CAN",
            board: "MFE_POS3_CAN",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MFE_POS3_CAN`
        };
static MatekG474DShot: Board = {
            friendlyName: "MatekG474-DShot",
            board: "MatekG474-DShot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekG474-DShot`
        };
static MatekG474GPS: Board = {
            friendlyName: "MatekG474-GPS",
            board: "MatekG474-GPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekG474-GPS`
        };
static MatekG474Periph: Board = {
            friendlyName: "MatekG474-Periph",
            board: "MatekG474-Periph",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekG474-Periph`
        };
static MatekH743periph: Board = {
            friendlyName: "MatekH743-periph",
            board: "MatekH743-periph",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekH743-periph`
        };
static MatekL431ADSB: Board = {
            friendlyName: "MatekL431-ADSB",
            board: "MatekL431-ADSB",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-ADSB`
        };
static MatekL431APDTelem: Board = {
            friendlyName: "MatekL431-APDTelem",
            board: "MatekL431-APDTelem",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-APDTelem`
        };
static MatekL431AUAV: Board = {
            friendlyName: "MatekL431-AUAV",
            board: "MatekL431-AUAV",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-AUAV`
        };
static MatekL431Airspeed: Board = {
            friendlyName: "MatekL431-Airspeed",
            board: "MatekL431-Airspeed",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Airspeed`
        };
static MatekL431BattMon: Board = {
            friendlyName: "MatekL431-BattMon",
            board: "MatekL431-BattMon",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-BattMon`
        };
static MatekL431BatteryTag: Board = {
            friendlyName: "MatekL431-BatteryTag",
            board: "MatekL431-BatteryTag",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-BatteryTag`
        };
static MatekL431DShot: Board = {
            friendlyName: "MatekL431-DShot",
            board: "MatekL431-DShot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-DShot`
        };
static MatekL431EFI: Board = {
            friendlyName: "MatekL431-EFI",
            board: "MatekL431-EFI",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-EFI`
        };
static MatekL431GPS: Board = {
            friendlyName: "MatekL431-GPS",
            board: "MatekL431-GPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-GPS`
        };
static MatekL431HWTelem: Board = {
            friendlyName: "MatekL431-HWTelem",
            board: "MatekL431-HWTelem",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-HWTelem`
        };
static MatekL431MagHiRes: Board = {
            friendlyName: "MatekL431-MagHiRes",
            board: "MatekL431-MagHiRes",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-MagHiRes`
        };
static MatekL431Periph: Board = {
            friendlyName: "MatekL431-Periph",
            board: "MatekL431-Periph",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Periph`
        };
static MatekL431Proximity: Board = {
            friendlyName: "MatekL431-Proximity",
            board: "MatekL431-Proximity",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Proximity`
        };
static MatekL431RC: Board = {
            friendlyName: "MatekL431-RC",
            board: "MatekL431-RC",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-RC`
        };
static MatekL431Rangefinder: Board = {
            friendlyName: "MatekL431-Rangefinder",
            board: "MatekL431-Rangefinder",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Rangefinder`
        };
static MatekL431Serial: Board = {
            friendlyName: "MatekL431-Serial",
            board: "MatekL431-Serial",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Serial`
        };
static MatekL431bdshot: Board = {
            friendlyName: "MatekL431-bdshot",
            board: "MatekL431-bdshot",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/MatekL431-bdshot`
        };
static NucleoG491: Board = {
            friendlyName: "Nucleo-G491",
            board: "Nucleo-G491",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Nucleo-G491`
        };
static NucleoL476: Board = {
            friendlyName: "Nucleo-L476",
            board: "Nucleo-L476",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Nucleo-L476`
        };
static NucleoL496: Board = {
            friendlyName: "Nucleo-L496",
            board: "Nucleo-L496",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Nucleo-L496`
        };
static Pixhawk6XPPPGW: Board = {
            friendlyName: "Pixhawk6X-PPPGW",
            board: "Pixhawk6X-PPPGW",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6X-PPPGW`
        };
static Pixracerperiph: Board = {
            friendlyName: "Pixracer-periph",
            board: "Pixracer-periph",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Pixracer-periph`
        };
static SierraF405: Board = {
            friendlyName: "Sierra-F405",
            board: "Sierra-F405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Sierra-F405`
        };
static SierraF412: Board = {
            friendlyName: "Sierra-F412",
            board: "Sierra-F412",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Sierra-F412`
        };
static SierraF9P: Board = {
            friendlyName: "Sierra-F9P",
            board: "Sierra-F9P",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Sierra-F9P`
        };
static SierraL431: Board = {
            friendlyName: "Sierra-L431",
            board: "Sierra-L431",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Sierra-L431`
        };
static SierraPrecisionPoint: Board = {
            friendlyName: "Sierra-PrecisionPoint",
            board: "Sierra-PrecisionPoint",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Sierra-PrecisionPoint`
        };
static SierraTrueNavIC: Board = {
            friendlyName: "Sierra-TrueNavIC",
            board: "Sierra-TrueNavIC",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueNavIC`
        };
static SierraTrueNavPro: Board = {
            friendlyName: "Sierra-TrueNavPro",
            board: "Sierra-TrueNavPro",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueNavPro`
        };
static SierraTrueNavProG4: Board = {
            friendlyName: "Sierra-TrueNavPro-G4",
            board: "Sierra-TrueNavPro-G4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueNavPro-G4`
        };
static SierraTrueNorth: Board = {
            friendlyName: "Sierra-TrueNorth",
            board: "Sierra-TrueNorth",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueNorth`
        };
static SierraTrueSpeed: Board = {
            friendlyName: "Sierra-TrueSpeed",
            board: "Sierra-TrueSpeed",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueSpeed`
        };
static TBSL431Airspeed: Board = {
            friendlyName: "TBS-L431-Airspeed",
            board: "TBS-L431-Airspeed",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/TBS-L431-Airspeed`
        };
static TBSL431BattMon: Board = {
            friendlyName: "TBS-L431-BattMon",
            board: "TBS-L431-BattMon",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/TBS-L431-BattMon`
        };
static TBSL431CurrMon: Board = {
            friendlyName: "TBS-L431-CurrMon",
            board: "TBS-L431-CurrMon",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/TBS-L431-CurrMon`
        };
static TBSL431PWM: Board = {
            friendlyName: "TBS-L431-PWM",
            board: "TBS-L431-PWM",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/TBS-L431-PWM`
        };
static VML431BatteryTag: Board = {
            friendlyName: "VM-L431-BatteryTag",
            board: "VM-L431-BatteryTag",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/VM-L431-BatteryTag`
        };
static VML431PeriphPico: Board = {
            friendlyName: "VM-L431-Periph-Pico",
            board: "VM-L431-Periph-Pico",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/VM-L431-Periph-Pico`
        };
static VML431SRVHub4CHP: Board = {
            friendlyName: "VM-L431-SRV-Hub-4CHP",
            board: "VM-L431-SRV-Hub-4CHP",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/VM-L431-SRV-Hub-4CHP`
        };
static ZubaxGNSS: Board = {
            friendlyName: "ZubaxGNSS",
            board: "ZubaxGNSS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/ZubaxGNSS`
        };
static f103ADSB: Board = {
            friendlyName: "f103-ADSB",
            board: "f103-ADSB",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f103-ADSB`
        };
static f103Airspeed: Board = {
            friendlyName: "f103-Airspeed",
            board: "f103-Airspeed",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f103-Airspeed`
        };
static f103GPS: Board = {
            friendlyName: "f103-GPS",
            board: "f103-GPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f103-GPS`
        };
static f103QiotekPeriph: Board = {
            friendlyName: "f103-QiotekPeriph",
            board: "f103-QiotekPeriph",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f103-QiotekPeriph`
        };
static f103RangeFinder: Board = {
            friendlyName: "f103-RangeFinder",
            board: "f103-RangeFinder",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f103-RangeFinder`
        };
static f303GPS: Board = {
            friendlyName: "f303-GPS",
            board: "f303-GPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f303-GPS`
        };
static f303HWESC: Board = {
            friendlyName: "f303-HWESC",
            board: "f303-HWESC",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f303-HWESC`
        };
static f303M10025: Board = {
            friendlyName: "f303-M10025",
            board: "f303-M10025",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f303-M10025`
        };
static f303M10070: Board = {
            friendlyName: "f303-M10070",
            board: "f303-M10070",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f303-M10070`
        };
static f303MatekGPS: Board = {
            friendlyName: "f303-MatekGPS",
            board: "f303-MatekGPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f303-MatekGPS`
        };
static f303PWM: Board = {
            friendlyName: "f303-PWM",
            board: "f303-PWM",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f303-PWM`
        };
static f303TempSensor: Board = {
            friendlyName: "f303-TempSensor",
            board: "f303-TempSensor",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f303-TempSensor`
        };
static f303Universal: Board = {
            friendlyName: "f303-Universal",
            board: "f303-Universal",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f303-Universal`
        };
static f405MatekAirspeed: Board = {
            friendlyName: "f405-MatekAirspeed",
            board: "f405-MatekAirspeed",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f405-MatekAirspeed`
        };
static f405MatekGPS: Board = {
            friendlyName: "f405-MatekGPS",
            board: "f405-MatekGPS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/f405-MatekGPS`
        };
static kha_eth: Board = {
            friendlyName: "kha_eth",
            board: "kha_eth",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/kha_eth`
        };
static mRoM10095: Board = {
            friendlyName: "mRo-M10095",
            board: "mRo-M10095",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRo-M10095`
        };
static mRoCANPWMM10126: Board = {
            friendlyName: "mRoCANPWM-M10126",
            board: "mRoCANPWM-M10126",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoCANPWM-M10126`
        };
static mRoKitCANrevC: Board = {
            friendlyName: "mRoKitCANrevC",
            board: "mRoKitCANrevC",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/mRoKitCANrevC`
        };
static rGNSS: Board = {
            friendlyName: "rGNSS",
            board: "rGNSS",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/rGNSS`
        };
static swboomf407: Board = {
            friendlyName: "sw-boom-f407",
            board: "sw-boom-f407",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/sw-boom-f407`
        };
static swnavf405: Board = {
            friendlyName: "sw-nav-f405",
            board: "sw-nav-f405",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/sw-nav-f405`
        };
static swsparf407: Board = {
            friendlyName: "sw-spar-f407",
            board: "sw-spar-f407",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/sw-spar-f407`
        };
static uavdevauavg4: Board = {
            friendlyName: "uav-dev-auav-g4",
            board: "uav-dev-auav-g4",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/uav-dev-auav-g4`
        };
static uavdevpowermodule: Board = {
            friendlyName: "uav-dev-powermodule",
            board: "uav-dev-powermodule",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/uav-dev-powermodule`
        };
static uavdev_m10s: Board = {
            friendlyName: "uav-dev_m10s",
            board: "uav-dev_m10s",
            hwDefDirectory: `${BuildLocation.buildFolder}/libraries/AP_HAL_ChibiOS/hwdef/uav-dev_m10s`
        };
    }